//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import com.github.braully.interfaces.ISystemEntity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import lombok.Data;

@Data
@MappedSuperclass
public abstract class AbstractSystemEntity extends AbstractEntity implements ISystemEntity {

    public AbstractSystemEntity() {

    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    protected Boolean editable;

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public boolean isPersisted() {
        return this.id != null && this.id > 0;
    }
}
