//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(schema = "financial")
public class AccountTransaction extends AbstractMigrableEntity implements Serializable {

    @Basic
    BigDecimal creditTotal;

    @Basic
    String observation;

    @Basic
    String typeOperation;

    @Basic
    String memo;

    @Basic
    Date datePrevist;

    @Basic
    Date dateExecuted;

    @Basic
    BigDecimal debitTotal;

    @Basic
    String typeTransaction;

    @Basic
    BigDecimal actualBalance;

    @Basic
    String typeMethod;

    @ManyToOne(targetEntity = Partner.class)
    Partner partner;

    @ManyToOne(targetEntity = Account.class)
    Account account;

    @ManyToOne(targetEntity = FinancialAccount.class)
    FinancialAccount financialAccount;

    @ManyToOne(targetEntity = AccountTransaction.class)
    AccountTransaction parentTransaction;

    @OneToMany(mappedBy = "parentTransaction")
    Set<AccountTransaction> childTransactions;

    @Basic
    String status;

    public AccountTransaction() {

    }

    public BigDecimal getCreditTotal() {
        return this.creditTotal;
    }

    public void setCreditTotal(BigDecimal creditTotal) {
        this.creditTotal = creditTotal;
    }

    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public String getTypeOperation() {
        return this.typeOperation;
    }

    public void setTypeOperation(String typeOperation) {
        this.typeOperation = typeOperation;
    }

    public String getMemo() {
        return this.memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public FinancialAccount getFinancialAccount() {
        return this.financialAccount;
    }

    public void setFinancialAccount(FinancialAccount financialAccount) {
        this.financialAccount = financialAccount;
    }

    public Date getDatePrevist() {
        return this.datePrevist;
    }

    public void setDatePrevist(Date datePrevist) {
        this.datePrevist = datePrevist;
    }

    public Date getDateExecuted() {
        return this.dateExecuted;
    }

    public void setDateExecuted(Date dateExecuted) {
        this.dateExecuted = dateExecuted;
    }

    public BigDecimal getDebitTotal() {
        return this.debitTotal;
    }

    public void setDebitTotal(BigDecimal debitTotal) {
        this.debitTotal = debitTotal;
    }

    public String getTypeTransaction() {
        return this.typeTransaction;
    }

    public void setTypeTransaction(String typeTransaction) {
        this.typeTransaction = typeTransaction;
    }

    public Partner getPartner() {
        return this.partner;
    }

    public void setPartner(Partner partner) {
        this.partner = partner;
    }

    public BigDecimal getActualBalance() {
        return this.actualBalance;
    }

    public void setActualBalance(BigDecimal actualBalance) {
        this.actualBalance = actualBalance;
    }

    public String getTypeMethod() {
        return this.typeMethod;
    }

    public void setTypeMethod(String typeMethod) {
        this.typeMethod = typeMethod;
    }

    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Set<AccountTransaction> getChildTransactions() {
        return childTransactions;
    }
}
