//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import com.github.braully.constant.StatusExecutionCycle;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(schema = "base")
public class BinaryFile extends AbstractStatusEntity implements Serializable {

    @Basic
    private String name;

    @Basic
    private String type;

    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date date;

    @Basic(fetch = FetchType.LAZY)
    private byte[] fileBinary;

    @Basic
    private String md5;

    @Basic
    private String pathCloud;

    @Basic
    private String pathLog;

    @Enumerated
    @Basic
    private StatusExecutionCycle statusExecution;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public byte[] getFileBinary() {
        return fileBinary;
    }

    public void setFileBinary(byte[] fileBinary) {
        this.fileBinary = fileBinary;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPathCloud() {
        return pathCloud;
    }

    public void setPathCloud(String pathCloud) {
        this.pathCloud = pathCloud;
    }

    public String getPathLog() {
        return pathLog;
    }

    public void setPathLog(String pathLog) {
        this.pathLog = pathLog;
    }

    public StatusExecutionCycle getStatusExecution() {
        return statusExecution;
    }

    public void setStatusExecution(StatusExecutionCycle statusExecution) {
        this.statusExecution = statusExecution;
    }

    public boolean isReady() {
        return this.statusExecution == StatusExecutionCycle.READY;
    }
}
