//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(schema = "financial")
public class FinancialAccount extends AbstractMigrableEntity implements Serializable {

    @ManyToOne
    protected Bank bank;

    @Basic
    private String number;

    @Basic
    private String agency;

    @Basic
    private String name;

    @Basic
    private String description;

    @Basic
    private String type;

    @Basic
    protected String codOfx;

    @ManyToOne(targetEntity = Account.class)
    private FinancialAccount parentAccount;

    public FinancialAccount() {

    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getAgency() {
        return this.agency;
    }

    public void setAgency(String agency) {
        this.agency = agency;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
