//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import com.github.braully.interfaces.IOrganiztionEntityDependent;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(schema = "sale")
@DiscriminatorValue("0")
@DiscriminatorColumn(discriminatorType = DiscriminatorType.INTEGER, name = "type_id",
        columnDefinition = "smallint default '0'", length = 1)
@Getter
@Setter
public class Inventory extends AbstractEntity implements IOrganiztionEntityDependent, Serializable {

    @ManyToOne
    Organization organization;

    @Basic
    String localization;

    @Basic
    String name;

    @Basic
    String description;

    @Basic
    String type;

    @Override
    protected String preToString() {
        return name;
    }
}
