//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "menu", schema = "security")
public class Menu extends AbstractLightRemoveEntity implements Serializable {

    @Basic
    private Integer sortIndex;

    @Basic
    private String name;

    @Basic
    private String link;

    @Basic
    private String icon;

    @OneToMany(targetEntity = Menu.class, mappedBy = "parent")
    private List<Menu> childs;

    @ManyToOne
    private Menu parent;

    @Basic
    private String value;

    public Menu() {

    }

    public Menu(String menu) {
        this.value = menu;
        this.name = menu;
    }

    public Integer getSortIndex() {
        return this.sortIndex;
    }

    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLink() {
        return this.link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public List<Menu> getChilds() {
        return this.childs;
    }

    public void setChilds(List<Menu> menuChilds) {
        this.childs = menuChilds;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Menu getPai() {
        return parent;
    }

    public void setPai(Menu pai) {
        this.parent = pai;
    }

    public Menu addChild(Menu menu) {
        if (this.childs == null) {
            this.childs = new ArrayList<>();
        }
        this.childs.add(menu);
        return this;
    }

    public Menu link(String link) {
        this.link = link;
        return this;
    }
}
