//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import static javax.persistence.TemporalType.DATE;

@Entity
@Table(schema = "base")
public class Partner extends AbstractMigrableEntity implements Serializable {

    @Basic
    private String phoneticName;

    @Basic
    private String name;

    @Basic
    private String attribute;

    @ManyToOne(cascade = CascadeType.ALL)
    private InfoExtra infoExtra;

    @Basic
    @Temporal(DATE)
    protected Date birthDate;

    public Partner() {

    }

    public String getPhoneticName() {
        return this.phoneticName;
    }

    public void setPhoneticName(String phoneticName) {
        this.phoneticName = phoneticName;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAttribute() {
        return this.attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    public InfoExtra getInfoExtra() {
        return infoExtra;
    }

    public void setInfoExtra(InfoExtra infoExtra) {
        this.infoExtra = infoExtra;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
}
