//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(schema = "base")
public class Phone extends AbstractEntity implements Serializable {

    @Basic
    private String number;

    @OneToMany(targetEntity = Partner.class)
    @JoinTable(schema = "base")
    private List<Partner> partner;

    @Basic
    private String observation;

    @Basic
    private String type;

    public Phone() {

    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public List<Partner> getPartner() {
        return this.partner;
    }

    public void setPartner(List<Partner> partner) {
        this.partner = partner;
    }

    public String getObservation() {
        return this.observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
