//
// This file was generated by the JPA Modeler
//
package com.github.braully.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(schema = "sale")
@Getter
@Setter
public class ProductPrice extends AbstractExpirableEntity implements Serializable {

    @ManyToOne
    Organization organization;

    @ManyToOne(targetEntity = Inventory.class)
    Inventory inventory;

    @ManyToOne(targetEntity = Product.class)
    Product product;

    String description;

    @Basic
    BigDecimal basePrice;

    @Basic
    BigDecimal fixedPrice;

    @Basic
    BigDecimal charge;

    @Basic
    Double taxPercent;

    @Basic
    Double profitPercent;

}
